### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by delgadom**

### CODE REVIEW

**Comment by delgadom** [comment]
my attempt at #18

**Comment by delgadom** [comment]
See the new readme at https://github.com/ClimateImpactLab/DataFS/tree/docs

One of the links won't work, because it references a page on readthedocs that won't be there until we merge this PR. wah wah

**Comment by jgerardsimcock** [comment]
LGTM

**Comment by jgerardsimcock** [comment]
Going to keep branch open so we can keep working on docs

**Pull request merged**
